repos:
-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    - id: black
      language_version: python3.11.9
-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    - id: flake8
      language: python
      entry: python3 -m flake8
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        language: python
        entry: "./run-mypy"
        language_version: python3.11
        additional_dependencies: ["mypy==1.12.0"]
        types: [python]
        require_serial: true
        verbose: true